version: "3"

services: 
  backend_django:
    restart: always
    build:
      .
    ports:
      - "8000:8000"
    volumes:
      - .:/inventory_checking
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "stocktalkingdb"
      POSTGRES_USER: "admintest"
      POSTGRES_PASSWORD: "admintest123"
    expose:
      - 5432
    ports:
      - "5432:5432"
