version: "3"

services: 
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "scratchdb"
      POSTGRES_USER: "scratch"
      POSTGRES_PASSWORD: "admin"
    expose:
      - 8888
    ports:
      - "8888:8888"

  backend_django:
    restart: always
    build:
      .
    ports:
      - "8000:8000"
    volumes:
      - .:/inventory_checking
    depends_on:
      - postgres
